# Generated by Django 5.0.6 on 2024-09-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("1", "Admin"),
                    ("2", "Planning"),
                    ("3", "Yarn Store"),
                    ("4", "Fabric Store"),
                    ("5", "Floor"),
                ],
                default="1",
                max_length=120,
            ),
        ),
    ]
