# Generated by Django 5.0.6 on 2024-09-13 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer_name", models.CharField(db_index=True, max_length=255)),
                ("order_no", models.CharField(db_index=True, max_length=255)),
                ("order_type", models.CharField(db_index=True, max_length=255)),
                (
                    "total_order_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("issue_date", models.DateField(db_index=True)),
                ("shipment_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["issue_date"], name="fabricmanag_issue_d_1f9b63_idx"
                    ),
                    models.Index(
                        fields=["shipment_date"], name="fabricmanag_shipmen_dd51de_idx"
                    ),
                    models.Index(
                        fields=["order_no"], name="fabricmanag_order_n_55ba46_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="fabricmanag_created_1b00b8_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="fabricmanag_updated_1dcd96_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style", models.CharField(db_index=True, max_length=244)),
                ("color", models.CharField(db_index=True, max_length=233)),
                ("fabric_design", models.CharField(db_index=True, max_length=233)),
                ("gsm", models.CharField(db_index=True, max_length=233)),
                ("finish_dia", models.CharField(db_index=True, max_length=233)),
                ("machine_dia", models.CharField(db_index=True, max_length=233)),
                ("machine_type", models.CharField(db_index=True, max_length=233)),
                (
                    "order_item_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fabricmanagement.order",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["style"], name="fabricmanag_style_209dcc_idx"),
                    models.Index(
                        fields=["created_at"], name="fabricmanag_created_260fb7_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="fabricmanag_updated_2843d4_idx"
                    ),
                ],
            },
        ),
    ]
