# Generated by Django 5.0.6 on 2024-09-15 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("email", models.EmailField(max_length=30)),
                ("address", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buyers_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MachineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machine_type_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_type_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(db_index=True, max_length=255)),
                ("order_type", models.CharField(db_index=True, max_length=255)),
                (
                    "total_order_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_knitcard_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_production_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("issue_date", models.DateField(db_index=True)),
                ("shipment_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fabricmanagement.buyer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style", models.CharField(db_index=True, max_length=244)),
                ("color", models.CharField(db_index=True, max_length=233)),
                ("fabric_design", models.CharField(db_index=True, max_length=233)),
                ("gsm", models.CharField(db_index=True, max_length=233)),
                ("finish_dia", models.CharField(db_index=True, max_length=233)),
                ("machine_dia", models.CharField(db_index=True, max_length=233)),
                ("machine_type", models.CharField(db_index=True, max_length=233)),
                (
                    "order_item_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_assign_qty",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "total_produce_qty",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "total_store_recv_qty",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "total_store_del_qty",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "total_challan_qty",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fabricmanagement.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("type", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unit_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_no", models.PositiveIntegerField(unique=True)),
                ("machine_name", models.CharField(max_length=50)),
                ("machine_brand", models.CharField(max_length=50)),
                ("machine_gauge", models.CharField(max_length=50)),
                ("machine_dia", models.PositiveIntegerField()),
                ("no_of_feeder", models.PositiveIntegerField()),
                ("rotation_per_minute", models.PositiveIntegerField()),
                ("accuracy", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "production_capacity_per_day",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_maintenance", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("loaded_status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fabricmanagement.machinetype",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fabricmanagement.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YarnCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yarn_count", models.CharField(max_length=70, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["yarn_count"], name="fabricmanag_yarn_co_4bfc8d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="YarnType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yarn_type", models.CharField(max_length=70, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["yarn_type"], name="fabricmanag_yarn_ty_63b833_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="YarnOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yarn_brand", models.CharField(max_length=50)),
                ("yarn_lot", models.CharField(max_length=50)),
                (
                    "stitch_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_yarn_receive_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_yarn_knitted_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yarn_orders",
                        to="fabricmanagement.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yarn_orders",
                        to="fabricmanagement.orderitem",
                    ),
                ),
                (
                    "yarn_count_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="yarn_orders",
                        to="fabricmanagement.yarncount",
                    ),
                ),
                (
                    "yarn_type_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="yarn_orders",
                        to="fabricmanagement.yarntype",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="buyer",
            index=models.Index(fields=["name"], name="fabricmanag_name_8bcb97_idx"),
        ),
        migrations.AddIndex(
            model_name="buyer",
            index=models.Index(fields=["email"], name="fabricmanag_email_f163ae_idx"),
        ),
        migrations.AddIndex(
            model_name="machinetype",
            index=models.Index(fields=["type"], name="fabricmanag_type_1cd651_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["issue_date"], name="fabricmanag_issue_d_1f9b63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["shipment_date"], name="fabricmanag_shipmen_dd51de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_no"], name="fabricmanag_order_n_55ba46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="fabricmanag_created_1b00b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["updated_at"], name="fabricmanag_updated_1dcd96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["style"], name="fabricmanag_style_209dcc_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["created_at"], name="fabricmanag_created_260fb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["updated_at"], name="fabricmanag_updated_2843d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["name"], name="fabricmanag_name_732683_idx"),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(
                fields=["machine_no"], name="fabricmanag_machine_345fc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(
                fields=["is_active"], name="fabricmanag_is_acti_09547b_idx"
            ),
        ),
    ]
