# Generated by Django 5.0.6 on 2024-09-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fabricmanagement", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="buyer_name",
            new_name="buyer",
        ),
    ]
