# Generated by Django 5.0.6 on 2024-09-28 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabricmanagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnitCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("knitcard_qty", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "produce_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "knitcard_no",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("knitting_start_date", models.DateField()),
                ("knitting_end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knitcards",
                        to="fabricmanagement.machine",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knitcards",
                        to="fabricmanagement.orderitem",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knitcards",
                        to="fabricmanagement.unit",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["knitcard_no"], name="fabricmanag_knitcar_6c67e9_idx"
                    )
                ],
            },
        ),
    ]
