# Generated by Django 5.0.6 on 2024-09-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabricmanagement", "0003_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
